import Navigation from "../components/Navigation";
import "../styles/globals.css";
import styles from "../styles/Layout.module.scss";

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body>
				<div className={styles.container}>
					<header className={styles.header}>
						<Navigation />
					</header>
					<main className={styles.main}>{children}</main>
					<footer className={styles.footer}>
						<p>&copy; 2025 AG-USA</p>
					</footer>
				</div>
			</body>
		</html>
	);
}
