import "mdb-react-ui-kit/dist/css/mdb.min.css";
import "@fortawesome/fontawesome-free/css/all.min.css";
import Navigation from "../components/Navigation";
import "../styles/globals.css";
import styles from "../styles/Layout.module.scss";
import "bootstrap/dist/css/bootstrap.min.css";
import Footer from "../components/Footer";

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<meta name="viewport" content="width=device-width, initial-scale=1" />

			<body>
				<div className={styles.container}>
					<header className={styles.header}>
						<Navigation />
					</header>
					<main className={styles.main}>{children}</main>
				</div>
				<Footer />
			</body>
		</html>
	);
}
